// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/project_status.proto

package project_status

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectStatusClient is the client API for ProjectStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectStatusClient interface {
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type projectStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectStatusClient(cc grpc.ClientConnInterface) ProjectStatusClient {
	return &projectStatusClient{cc}
}

func (c *projectStatusClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/project_status.ProjectStatus/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectStatusClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/project_status.ProjectStatus/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectStatusServer is the server API for ProjectStatus service.
// All implementations must embed UnimplementedProjectStatusServer
// for forward compatibility
type ProjectStatusServer interface {
	Find(context.Context, *FindRequest) (*FindResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedProjectStatusServer()
}

// UnimplementedProjectStatusServer must be embedded to have forward compatible implementations.
type UnimplementedProjectStatusServer struct {
}

func (UnimplementedProjectStatusServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedProjectStatusServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProjectStatusServer) mustEmbedUnimplementedProjectStatusServer() {}

// UnsafeProjectStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectStatusServer will
// result in compilation errors.
type UnsafeProjectStatusServer interface {
	mustEmbedUnimplementedProjectStatusServer()
}

func RegisterProjectStatusServer(s grpc.ServiceRegistrar, srv ProjectStatusServer) {
	s.RegisterService(&ProjectStatus_ServiceDesc, srv)
}

func _ProjectStatus_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectStatusServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_status.ProjectStatus/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectStatusServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectStatus_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectStatusServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project_status.ProjectStatus/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectStatusServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectStatus_ServiceDesc is the grpc.ServiceDesc for ProjectStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project_status.ProjectStatus",
	HandlerType: (*ProjectStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _ProjectStatus_Find_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectStatus_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/project_status.proto",
}
